name: CD

on:
    workflow_dispatch:
        inputs:
            vizzu:
                description: 'Vizzu version to tag'
                required: true
            workspace:
                description: 'Yarn workspace to use'
                required: true
            release_workspace:
                description: 'True to print to STDOUT'
                default: false
                type: boolean

jobs:
    publish:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Enable Corepack
              run: |
                  corepack enable

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'yarn'
                  cache-dependency-path: 'yarn.lock'

            - name: Init dev environment
              run: |
                  yarn --immutable

            - name: Release package
              if: ${{ inputs.release_workspace }}
              run: |
                  echo "npmAuthToken: \"${VIZZUHQ_NPM_API}\"" > .yarnrc.yml
                  yarn workspace ${{ inputs.workspace }} npm publish
              env:
                  VIZZUHQ_NPM_API: ${{ secrets.VIZZUHQ_NPM_API }}

            - name: Tag package
              run: |
                  echo "npmAuthToken: \"${VIZZUHQ_NPM_API}\"" > .yarnrc.yml
                  VERSION="0.9.2"
                  TAGS=("vizzu-$VERSION" "vizzu-${VERSION%.*}" "vizzu-${VERSION%%.*}")

                  for TAG in "${TAGS[@]}"; do
                     echo $TAG
                  done
              env:
                  VIZZUHQ_NPM_API: ${{ secrets.VIZZUHQ_NPM_API }}
